"""empty message

Revision ID: 203da67839e8
Revises: c580071f5a27
Create Date: 2026-08-05 08:35:48.896569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203da67839e8'
down_revision = 'c580071f5a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('medical_appointment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('state', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_appointment', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
