"""empty message

Revision ID: 287634f8f5a5
Revises: 2c22ae841493
Create Date: 2026-07-29 13:10:03.430488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287634f8f5a5'
down_revision = '2c22ae841493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('birthDate', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('legalDocument', sa.String(length=9), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('pc', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('adress', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['legalDocument'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('adress')
        batch_op.drop_column('pc')
        batch_op.drop_column('city')
        batch_op.drop_column('legalDocument')
        batch_op.drop_column('birthDate')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
