"""empty message

Revision ID: 2c22ae841493
Revises: 0763d677d453
Create Date: 2026-07-27 00:35:27.917947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c22ae841493'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('CIF', sa.String(length=50), nullable=True),
    sa.Column('adress', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('creationDate', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('pc', sa.String(length=20), nullable=True),
    sa.Column('iconUrl', sa.String(length=255), nullable=True),
    sa.Column('IBAN', sa.String(length=34), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelter')
    # ### end Alembic commands ###
