"""empty message

Revision ID: 551d960c52d8
Revises: 2d463d93318b
Create Date: 2026-07-29 17:46:52.592955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551d960c52d8'
down_revision = '2d463d93318b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['password'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
