"""empty message

Revision ID: 56c64f7b6012
Revises: 2117d7ea7370
Create Date: 2026-08-19 03:33:17.085921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c64f7b6012'
down_revision = '2117d7ea7370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinarian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('icon_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinarian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
