"""empty message

Revision ID: 6900b6ad6820
Revises: c580071f5a27
Create Date: 2026-08-05 09:06:09.905206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6900b6ad6820'
down_revision = 'c580071f5a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('medical_appointment', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
