"""empty message

Revision ID: 833d92b709ad
Revises: eaaec80a18c7
Create Date: 2026-07-31 10:39:20.948086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833d92b709ad'
down_revision = 'eaaec80a18c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))

    with op.batch_alter_table('veterinarian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinarian', schema=None) as batch_op:
        batch_op.drop_column('password')

    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
