"""empty message

Revision ID: 949923954277
Revises: 98aa516d9abb
Create Date: 2026-08-01 20:24:26.705013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949923954277'
down_revision = '98aa516d9abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cif', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['cif'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cif')

    # ### end Alembic commands ###
