"""empty message

Revision ID: c91487136673
Revises: 7bcdf5f56bab
Create Date: 2026-08-18 18:33:05.205023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91487136673'
down_revision = '7bcdf5f56bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinarian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('icon_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinarian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
