"""empty message

Revision ID: ebe4ed3b0e91
Revises: 40947dca7989
Create Date: 2026-07-28 23:32:58.058343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe4ed3b0e91'
down_revision = '40947dca7989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breedName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breedName')
    )
    op.create_table('shelter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('cif', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('pc', sa.String(length=20), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif'),
    sa.UniqueConstraint('email')
    )
    op.create_table('veterinarian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('pc', sa.String(length=20), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medical_appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('veterinarian_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.String(length=20), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['veterinarian_id'], ['veterinarian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'breed', ['breed_id'], ['id'])
        batch_op.create_foreign_key(None, 'shelter', ['shelter_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('legal_document', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pc', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['legal_document'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('city')
        batch_op.drop_column('pc')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('address')
        batch_op.drop_column('legal_document')
        batch_op.drop_column('name')

    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('medical_appointment')
    op.drop_table('veterinarian')
    op.drop_table('shelter')
    op.drop_table('breed')
    # ### end Alembic commands ###
